engines:
  eslint:
    enabled: true
    checks:
      import/no-absolute-path:
        enabled: false
ratings:
  paths:
  - "imports/**"
  - "client/*"
  - "server/**"
exclude_paths:
- "client/lib/**"
- ".meteor/**"
- "node_modules/**"
